version: '3'

services: 

  backend:
    build:
      context: './backend'
      dockerfile: 'Dockerfile.backend'
    container_name: 'noticrawl_backend'
    depends_on:
      - database
    ports:
      - '$APP_PORT:8000'
    volumes: 
      - './frontend/build:/frontend/build:ro'
      - './backend/src:/app/src'
      - './logs:/app/logs'
    environment: 
      SETTINGS_FILE_FOR_DYNACONF: '["database.secrets.toml", "auth.secrets.toml"]'


  database:
    image: postgres
    container_name: postgres
    restart: always
    hostname: $DB_HOST
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    ports:
      - '$DB_PORT:5432'
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD

volumes: 
  postgres-data: