version: '3'

services: 

  backend:
    build:
      context: './'
      dockerfile: './backend/Dockerfile.backend'
    container_name: 'noticrawl_backend'
    depends_on:
      - database
    ports:
      - '$APP_PORT:8000'
    volumes: 
      - './frontend/build:/frontend/build:ro'
      - './.env:/app/src/.env'
      - './backend/src:/app/src'

  database:
    image: postgres
    container_name: postgres
    restart: always
    hostname: $DB_HOST
    volumes:
      # - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres-data:/var/lib/postgresql/data 
    ports:
      - '$DB_PORT:5432'
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD

volumes: 
  postgres-data: