version: '3'
services: 
  backend:
    container_name: 
        noticrawl_backend
    build:
        context: './backend/'
        dockerfile: Dockerfile.backend
    ports: 
         - '8000:8000'
    volumes: 
         - './backend/src:/backend/src'
