version: '3.4'

services: 

  app:
    image: noticrawl:latest
    container_name: 'noticrawl_app'
    depends_on:
      - database
    ports:
      - '$APP_PORT:8000'
    volumes: 
      - './backend/src:/app/backend/src'
      - './logs:/app/logs'
    environment: 
      SETTINGS_FILE_FOR_DYNACONF: '["database.secrets.toml", "auth.secrets.toml", "email.secrets.toml", "crawling.config.toml"]'


  database:
    image: postgres
    container_name: postgres
    restart: always
    hostname: $DB_HOST
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    ports:
      - '$DB_PORT:5432'
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD

volumes: 
  postgres-data: