version: '3'

services: 
  backend:
    build:
      context: './backend/'
      dockerfile: Dockerfile.backend
    container_name: 'noticrawl_backend'
    depends_on:
      - database
    ports:
      - '8000:8000'
    volumes: 
      - './backend/src:/app/src'
      - './frontend/build:/frontend/build'

  databse:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres-data:/var/lib/postgresql/data 
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

volumes: 
  postgres-data: