FROM python:3.7

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

EXPOSE 8000

WORKDIR /app

COPY ./backend/poetry.lock ./backend/pyproject.toml ./
RUN pip install -q poetry==1.0.* && \
    poetry config virtualenvs.create false && \
    poetry install

COPY ./backend/src ./src

ENTRYPOINT ["poetry"]
CMD ["run", "task", "dev-server"]